[package]
name = "lily"
version = "0.1.0"
description = "CLI App"
authors = ["you"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri = { version = "2.1.1", features = ["unstable"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
twinleaf = "1.1.0"
getopts = "0.2"
bytemuck = "1.9"
pancurses = "0.17"
serialport = "*"
byteorder = "1.4"

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }








