[package]
name = "lily"
version = "0.1.0"
description = "Sensor graph monitor app"
authors = ["Ilysia Krzywonos"]
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "2.1.1", features = ["unstable"] }
tauri-plugin-shell = "2"
crossbeam = "0.8.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
twinleaf = "1.2.0"
getopts = "0.2"
welch-sde = "0.1.0"

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }






