[package]
name = "lily"
version = "0.1.0"
description = "CLI App"
authors = ["you"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri = { version = "1.8.0", features = [ "shell-open"] }
twinleaf = "1.0.0"
getopts = "0.2"
bytemuck = "1.9"
pancurses = "0.17"
serialport = "*"
byteorder = "1.4"

[build-dependencies]
tauri-build = { version = "1.0", features = [] }







