// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnMeta = { stream_id: number, index: number, data_type: string, name: string, units: string, description: string, };
