// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSet } from "./HealthSet";
import type { StatisticSet } from "./StatisticSet";

export type ColumnStatistics = { latest_value: number, persistent: StatisticSet, window: StatisticSet, persistent_health: HealthSet, window_health: HealthSet, };
