// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataColumnId = { port_url: string, device_route: string, stream_id: number, column_index: number, };
