// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeStreamInfo } from "./FeStreamInfo";

export type FeDeviceMeta = { name: string, serial: string, firmware: string, route: string, url: string, streams: Array<FeStreamInfo>, children: Array<FeDeviceMeta> | null, };
