// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeColumnInfo } from "./FeColumnInfo";

export type FeStreamInfo = { id: number, name: string, columns: Array<FeColumnInfo>, };
