// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetrendMethod } from "./DetrendMethod";

export type FftConfig = { window_seconds: number, detrend_method: DetrendMethod, };
