// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthSet = { gap_count: bigint, nan_count: bigint, gap_mean: number, gap_min: number, gap_max: number, };
