// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataFilter = "Unfiltered" | "FirstOrderCascade1" | "FirstOrderCascade2" | { "Unknown": number };
