// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlotData = { timestamps: Array<number>, series_data: Array<Array<number>>, };
