// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortState = "Idle" | "Connecting" | "Connected" | "Discovery" | "Streaming" | "Reconnecting" | "Disconnected" | { "Error": string };
