// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RpcErrorCode = "NoError" | "Undefined" | "NotFound" | "MalformedRequest" | "WrongSizeArgs" | "InvalidArgs" | "ReadOnly" | "WriteOnly" | "Timeout" | "Busy" | "WrongDeviceState" | "LoadFailed" | "LoadRpcFailed" | "SaveFailed" | "SaveWriteFailed" | "Internal" | "OutOfMemory" | "OutOfRange" | { "Unknown": number };
