// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcErrorPayload } from "./RpcErrorPayload";

export type RpcError = { "type": "ExecError", "payload": RpcErrorPayload } | { "type": "SendFailed", "payload": string } | { "type": "RecvFailed", "payload": string } | { "type": "TypeError" } | { "type": "AppLogic", "payload": string };
