// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RpcErrorCode } from "./RpcErrorCode";

export type RpcErrorPayload = { id: number, error: RpcErrorCode, extra: Array<number>, };
