// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RpcMeta = { name: string, size: number, permissions: string, arg_type: string, readable: boolean, writable: boolean, persistent: boolean, unknown: boolean, value: any, };
