// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataEpoch } from "./MetadataEpoch";
import type { MetadataFilter } from "./MetadataFilter";

export type SegmentMeta = { stream_id: number, segment_id: number, flags: number, time_ref_epoch: MetadataEpoch, time_ref_serial: string, time_ref_session_id: number, start_time: number, sampling_rate: number, decimation: number, filter_cutoff: number, filter_type: MetadataFilter, };
