// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataColumnId } from "./DataColumnId";
import type { ViewConfig } from "./ViewConfig";

export type SharedPlotConfig = { plot_id: string, data_keys: Array<DataColumnId>, max_sampling_rate: number, view_config: ViewConfig, };
