// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatisticSet } from "./StatisticSet";

export type StreamStatistics = { latest_value: number, persistent: StatisticSet, window: StatisticSet, };
