// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamMeta = { stream_id: number, name: string, n_columns: number, n_segments: number, sample_size: number, buf_samples: number, };
