// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamStats = { mean: number, ema: number, min: number, max: number, latest_value: number, count: number, };
