// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimationMethod } from "./DecimationMethod";

export type TimeseriesConfig = { decimation_method: DecimationMethod, window_seconds: number, resolution_multiplier: number, };
