// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceMeta } from "./DeviceMeta";
import type { PortState } from "./PortState";
import type { UiStream } from "./UiStream";

export type UiDevice = { url: string, route: string, state: PortState, meta: DeviceMeta, streams: Array<UiStream>, };
