// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMeta } from "./ColumnMeta";
import type { SegmentMeta } from "./SegmentMeta";
import type { StreamMeta } from "./StreamMeta";

export type UiStream = { meta: StreamMeta, segment: SegmentMeta | null, columns: Array<ColumnMeta>, effective_sampling_rate: number, };
